# Generated by Django 4.2.5 on 2023-09-17 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('detail', models.CharField(blank=True, max_length=1000)),
                ('like', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Wiki.language')),
            ],
        ),
    ]
