# Generated by Django 4.2.5 on 2023-09-17 23:57

import datetime
from django.db import migrations
import django.utils.timezone
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Wiki', '0003_alter_child_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='full_description',
            field=django_ckeditor_5.fields.CKEditor5Field(default=datetime.date(2023, 9, 18), verbose_name='Полное описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='child',
            name='short_description',
            field=django_ckeditor_5.fields.CKEditor5Field(default=datetime.date(2023, 9, 18), max_length=500, verbose_name='Краткое описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='language',
            name='full_description',
            field=django_ckeditor_5.fields.CKEditor5Field(default=datetime.date(2023, 9, 18), verbose_name='Полное описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='language',
            name='short_description',
            field=django_ckeditor_5.fields.CKEditor5Field(default=django.utils.timezone.now, max_length=500, verbose_name='Краткое описание'),
            preserve_default=False,
        ),
    ]
